### ISSUE TITLE
__init__ arguments are being replaced by *args, **kwargs

### ISSUE THREAD

**Issue by polakowo** [pdoc3/pdoc#191]
The following code
```
import plotly.graph_objects as go

class FigureWidget(go.FigureWidget):
    def __init__(self):
        """Documentation."""
        pass
```

Produces the following documentation

![Screen Shot 2020-04-28 at 19 14 43](https://user-images.githubusercontent.com/2664108/80517270-1c7f9380-8985-11ea-9840-6ba84c8a8e9e.png)

Although I clearly defined that the `__init__` method should have no arguments, it shows `*args` and `**kwargs` in the signature. Are there any caveats in subclassing third-party classes? Also any ideas how to unveil the "real" signature?

**Comment by kernc** [comment]
pdoc delegates to `inspect.signature()`:
https://github.com/pdoc3/pdoc/blob/004204320773cb98a8f0cd5fa82e8095f517e488/pdoc/__init__.py#L1214
Which, I think, apparently, prefers `__new__()`.
```py
>>> import plotly.graph_objects as go
                                                     
>>> class FigureWidget(go.FigureWidget): 
...     def __init__(self): 
...         """Documentation.""" 
...         pass                                                                              

>>> inspect.signature(FigureWidget)                                                           
<Signature (*args, **kwargs)>

>>> print(inspect.getsource(go.FigureWidget.__new__))                                         
    def __new__(cls, *args, **kwargs):
        # This is needed because object.__new__ only accepts
        # the cls argument.
        ...
```
You're experiencing a somewhat border case, and a likely violation of [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), so I'm leaning to wontfix.

Try if overriding `__new__()` works for you.

**Comment by kernc** [comment]
Work around by overriding `__new__`; should work.

**Comment by RaduG** [comment]
I want to re-raise this as it is quite an annoying problem especially when using `Generic`. Take this code:

```python
class A(Generic[T]):
    def __init__(self, a, b):
        ...
```

Because `typing.Generic` overrides `__new`, `inspect.signature` will always return its signature which clearly is not preferable. What we did to overcome this is make a change in `Function._params` to use `inspect.signature(doc_obj.obj.__init__)` if defined which fixed the problem. I don't know if there is a genuine use case for using `__new__` in docs if `__init__` is defined, but would you consider having a configuration parameter to drive this? I'm happy to do the PR if so.

**Comment by kernc** [comment]
@RaduG Sure, let's try it. I've no problem skipping the parameter and making it the default, if it works. :+1:
