### ISSUE TITLE
latex support

### ISSUE THREAD

**Issue by koaning** [pdoc3/pdoc#28]
Does `pdoc3` offer mathematical rendering via something like `MathJax`? I wouldn't know how to implement it but I'd be willing to investigate if people are open to this feature.

**Comment by kernc** [comment]
This use case had been accounted for. You should be able to make a template file _head.mako_ with contents like:
```html
<script async defer src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js"></script>
```
Then run pdoc with `--template-dir` pointing to the directory containing this overridden template file (see [custom templating documentation](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates)).

Afterwards, $$-delimited LaTeX blocks should render in symbols.

**Comment by kernc** [comment]
As of https://github.com/pdoc3/pdoc/pull/74, you should be able to run pdoc with `pdoc --config latex_math=True ...` for seamless MathJax support.

Duplicate of https://github.com/pdoc3/pdoc/issues/70.

**Comment by paloha** [comment]
Hello @kernc I would like to ask about `$` inline math support. I thought this was supported, but now I realized only `$$` for blocks of math are supported. I described my situation here in a [GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/339109#note_985696354). The result of this issue is that basically GitLab now finally supports `$...$` and `$$...$$` for math. This is in sync with GitHub :confetti_ball: It also works in the `.pdf` output obtained by piping `pdoc` to `pandoc`. Unfortunately, it does not work in your `html` output even with `--config latex_math=True`. I believe it would be reasonable to have a default which is in sync with the big players like GitHub and GitLab. 

For those who want a workaround: Copy the `head.mako` to your desired location, fill it with code from [this answer](https://tex.stackexchange.com/questions/27633/mathjax-inline-mode-not-rendering), and then compile your documentation with custom `--template-dir` as @kernc suggested [here](https://github.com/pdoc3/pdoc/issues/28#issuecomment-463169239), a few comments above.
