### ISSUE TITLE
[Question] Is there any way to turn off specific functionality?

### ISSUE THREAD

**Issue by zerosheepmoo** [pdoc3/pdoc#351]
I hope there is an option to turn off specific functionality, such as `inherited_members`.
I cannot discover the way to do it in the official documents.
Sometimes, people don't want to know too specific hierarchy, only desire simple skeleton of certain classes or methods.
This can occur when using 3rd party libs already documented well and when I extend the class of it.

By the way, I couldn't find the discussion community, so I've asked here. If there is someone who knows such channel, let me know.

+added) I know pdoc3 provides `__pdoc__` overriding. But that is quite limited, and to achieve the goal, too many configurations required.

### Additional info

- pdoc version: 0.10.0

**Comment by kernc** [comment]
> I hope there is an option to turn off specific functionality, such as `inherited_members`.

Pdoc3 uses [_config.mako_ template](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates) as the configuration file. You can provide your custom _config.mako_ and run with `--template-dir`, or override individual configuration options with `--config`, e.g. `pdoc --config show_inherited_members=False my_project`.

Since `show_inherited_members=False` is the default, I suspect you mean to hide "Inherited members" list completely. Unfortunately, this is part of the default _html.mako_ template and you'd need to modify it yourself.
https://github.com/pdoc3/pdoc/blob/f358893e4fcfd7f29857a7ff5491b606ff146d39/pdoc/templates/html.mako#L251-L270

**Comment by zerosheepmoo** [comment]
THANKs!
