### ISSUE TITLE
test_Class_params fails in the released 0.10.0 version

### ISSUE THREAD

**Issue by catern** [pdoc3/pdoc#355]
### Expected Behavior

All tests pass - they were run as part of this package update: https://github.com/NixOS/nixpkgs/pull/135261

### Actual Behavior

test_Class_params fails with
```
======================================================================
FAIL: test_Class_params (pdoc.test.ApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pdoc3-0.10.0/pdoc/test/__init__.py", line 100, in wrapper
    func(*args, **kwargs)
  File "/build/pdoc3-0.10.0/pdoc/test/__init__.py", line 1055, in test_Class_params
    self.assertEqual(pdoc.Class('G2', mod, G2).params(), ['*args', '**kwds'])
AssertionError: Lists differ: [] != ['*args', '**kwds']

Second list contains 2 additional elements.
First extra element 0:
'*args'

- []
+ ['*args', '**kwds']
```

### Steps to Reproduce

Run the tests on version 0.10.0 on PyPI. We're doing through `python setup.py test`.

### Additional info

- pdoc version: 0.10.0

**Comment by catern** [comment]
This test failure was introduced in commit d68abccc5b616917a092ba2b940dd96112090826 and is present in CPython 3.9 and not present in CPython 3.8.

**Comment by catern** [comment]
Which was introduced by PR #242 - @RaduG do you know what might be the right fix for this test failure?

**Comment by RaduG** [comment]
Hi @catern, this issue is caused by Python's `typing.Generic` class:
- in (and up to) 3.8, `typing.Generic` [defines a `__new__` magic method](https://github.com/python/cpython/blob/5a42a49477cd601d67d81483f9589258dccb14b1/Lib/typing.py#L845)
- [in 3.9 the method was removed](https://github.com/python/cpython/blob/f1d5cdef57fea961646c52db7a60d1f110e0eaa6/Lib/typing.py#L957)

The fix would be to stop using `typing.Generic` as a base and just create a base class that implements `__new__`. Happy to do this.
