### ISSUE TITLE
Article about pdoc3

### ISSUE THREAD

**Issue by tirthajyoti** [pdoc3/pdoc#360]
Just FYI, I wrote an article featuring your package on Medium. You can refer to it if you like.

**[How to Generate Professional API Docs in Minutes from Docstrings](https://towardsdatascience.com/how-to-generate-professional-api-docs-in-minutes-from-docstrings-aed0341bbda7)**

**Comment by kernc** [comment]
A few comments:
> ```
> def mult(num1, num2=1):
>     """
>     Multiplies two numbers
>     
>     Args:
>     
>     `num1`: The first number
>         
>     `num2`: The second number, default `1`
>     
>     Returns:
>     
>     The result of the **multiplication** process
>     """
> ```

Rather than styling with Markdown, a better way is to use [Numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#parameters)/[Google-style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) docstring formats when specifying parameters and return values.


> ~~~
> """
> ...
> Handles exception by a check,
>    
>     ```python
>     if num2 != 0:
>         return (num1/num2)
>     else:
>         raise ValueError('The second argument cannot be zero')
>     ```    
> """
> ~~~

In Markdown, you _either_ indent the verbatim code block one level (four spaces) _or_ make it a [fenced code block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks), but not both at the same time (unless you want that ```` ```python ```` header line shown as part of the code).

-----

I'd also mention fairly useful configuration via [_config.mako_ and related templates](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates).

Otherwise looks good. Thanks! :heart_decoration: :medal_sports:
